### ISSUE TITLE
delete PROP_CARET_SHAPE_mmm

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cudax_lib#19]
i deleted it in local copy. i dont do PullReq since my version differs.

**Comment by Alexey-T** [comment]
@kvichans GH works

**Comment by Alexey-T** [comment]
@kvichans  Сравните с моей копией- где я удалял вот это старое АПИ

**Comment by kvichans** [comment]
Новая версия создана из вашей `0.6.5.at 2018-10-22`
