### ISSUE TITLE
Deleting // comments

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cudax_lib#20]
надо бы отсекать это только ВНЕ строк. значение опции может быть с '//'.

**Comment by kvichans** [comment]
Не понял идею. Что "надо бы"?

**Comment by Alexey-T** [comment]
Поясню
Есть строка в Json 
nnnn: “ddd//ddd//ddd”, //eee

 Ваш код должен отсекать коммент только где //еее

**Comment by kvichans** [comment]
Цель понятна (я и сам этого хочу)
Как это реализовать?

**Comment by Alexey-T** [comment]
Проходить от начала строки и учитывать кавычку, удалить от // вне кавычек

**Comment by kvichans** [comment]
попробую...

**Comment by Alexey-T** [comment]
жду доделки этого для новой беты Куд.

**Comment by kvichans** [comment]
Обновил ГХ
Все случаи не понимаю как реализовать
Сделал так
- удаляются строки целиком, если они начинаются на // (мб после пробелов)
- удаляются концы строк после //, если в них нет "

Так что, если кто-то вставит в комментарий заковыченный текст
`"a": 123 // My "a"`
то такой комментарий останется и даст сбой.

**Comment by Alexey-T** [comment]
ето как-то криво. надо так-

- идем от начала строки
- ищем каждый //
- если до него четное число " , то ето коммент - отсекаем. если нечетное - не коммент

**Comment by kvichans** [comment]
это тоже криво - вот пример
`"a": "1\"//2"`

**Comment by Alexey-T** [comment]
тогда еще надо игнорить кавычки в виде 

    \"

**Comment by kvichans** [comment]
похоже это тоже еще не предел - можно найти контрпример

**Comment by Alexey-T** [comment]
тогда надо пропускать - когда "внутри кавычек", все пары "\ символ"

**Comment by kvichans** [comment]
слишком заморочно - оставим как сейчас

**Comment by Alexey-T** [comment]
Как тебе такое Илон Маск
```
import os
from cudatext import *

def strip_cmt(s):

    i = 0
    q = False
    while i<len(s):
        ch = s[i]
        if ch=='\\':
            i += 2
        else:
            if ch=='"':
                q = not q
            else:
                if s[i:i+2]=='//' and not q:
                    return s[:i]
            i += 1
            
    return s

    

class Command:
    
    def run(self):
        s = r"""  "oo" = "dd//\"dd" //eee //ee"""
        print(strip_cmt(s))
        
```

**Comment by kvichans** [comment]
Взял ваш код. Обновил ГХ
