### ISSUE TITLE
0.4.3

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cudax_lib#4]
запостил 2 комента, в коде изменения, там можно жать + и постить.

**Comment by kvichans** [comment]
Куда "запостил"? Где "там жать"?

**Comment by Alexey-T** [comment]
Сюда https://github.com/kvichans/cudax_lib/commit/e7352568e597841e70c248b19d9fcf40eff634cc
там с серед.

**Comment by kvichans** [comment]
ок, нашел
поправил код
