### ISSUE TITLE
Format for menu config

### ISSUE THREAD

**Issue by kvichans** [kvichans/cudax_lib#5]
Предлагаю такой формат для конфигуратора меню в json файле

```
{"top-file":
    {"how":"clear"
    ,"sub":
    [   {"cap":"Open..."            ,"cmd":"cmd_FileOpen"}
    ,   {"cap":"Open recent"        ,"cmd":"recents"}
    ,   {"cap":"-"}
    ,   {"cap":"Encoding"           ,"sub":
        [   {"cap":"Reload as"      ,"sub":
            [    {"cap":"ANSI"      ,"cmd":"cmd_Encoding_ansi_Reload"}
            ,    {"cap":"UTF-8"     ,"cmd":"cmd_Encoding_utf8nobom_Reload"}
            ]}
        ,    {"cap":"Convert to"    ,"sub":
            [    {"cap":"ANSI"      ,"cmd":"cmd_Encoding_ansi_NoReload"}
            ,    {"cap":"UTF-8"     ,"cmd":"cmd_Encoding_utf8nobom_NoReload"}
            ]}
        ]}
    ,   {"cap":"Exit"               ,"cmd":"cmd_FileExit"}
    ]}
,"top-edit":
    {"how":"clear"
    ,"sub":
    [   {"cap":"Undo"               ,"cmd":"cmd_FileExit"}
    ,   {"cap":"Redo"               ,"cmd":"cmd_FileExit"}
    ]}
}
```
1. На верхнем уровне могу быть только ключи из списка (пока нет Options и Help)
   `"top" "top-file" "top-edit" "top-sel" "top-sr" "top-view" "text"`
2. Пара `"how":"clear"` означает, что перед заполнением подменю нужно очистить. При `"how":"add"` элементы будут добавляться в конец.
3. Значением для `"cmd"` может быть 
   - `"<имя переменной>"` из `cudatext_cmd.py` 
   - `"<имя модуля>,<имя команды>"` (для плагин-команды)
   - одно из списка  `"recents"` `"themes"` `"plugins"`

**Comment by Alexey-T** [comment]
Наверное это нормальный формат..

**Comment by Alexey-T** [comment]
наверное не нужно: how: clear. how: add.
