### ISSUE TITLE
How to config menu on start?

### ISSUE THREAD

**Issue by kvichans** [kvichans/cudax_lib#6]
Нужен пример запуска плагина при старте Куд

**Comment by Alexey-T** [comment]
я уже показал демо. там это есть.

**Comment by kvichans** [comment]
не нашел как вызывать на старте
вижу только `def on_focus`

**Comment by Alexey-T** [comment]
если в него - msg_box, то р-ет?

**Comment by kvichans** [comment]
?

**Comment by Alexey-T** [comment]
попробуйте в него добавить msgbox.
он при старте должен сработать

**Comment by kvichans** [comment]
Не запускается
Содержимое install.inf

```
[info]
title=mn
desc=--
type=cudatext-plugin
subdir=cuda_mn

[item1]
section=events
events=on_focus 
```

Содержимое **init**.py

```
class Command:
    ini=False
    def run(self):
        msg_box('hhh', MB_OK)

    def on_focus(self, ed_self):
        if self.ini: return
        self.ini=True
        msg_box('init', MB_OK) 
```

**Comment by kvichans** [comment]
Нужно ли что-то добавлять в plugins.json?
Если "нужно", то вот так правильно?

```
  "events" : {
    "cuda_mn" : {
      "00" : {
        "proc" : "on_focus"
      }
    }
  },
  "commands" : {...
```

**Comment by Alexey-T** [comment]
не нужно, у меня плагин работает

**Comment by Alexey-T** [comment]
on-focus вызывается.

**Comment by kvichans** [comment]
То что у меня ни один из msg_box не сработал - это симптом чего-то?

**Comment by Alexey-T** [comment]
не знаю.

**Comment by kvichans** [comment]
может нужно было "установить" плагин, а не просто скопировать его в папку py?

**Comment by Alexey-T** [comment]
да! установить

**Comment by kvichans** [comment]
Я крайне не доверяю всем _автоматам_.
Как руками его _установить_, без открытия zip в редакторе?

**Comment by kvichans** [comment]
События on_app_start не планируется?
Вы предлагаете пользоваться on_focus - это явно не очень удачный способ.

А как будет оформляться и разруливаться несколько реакций на одно событие?
Если я оформлю замену меню по on_focus, а другой плагин тоже захочет реагировать на получение фокуса, то 
- что нужно будет делать?
- может ли один плагин запретить получать событие другому?

**Comment by kvichans** [comment]
Конфигуратор меню (метод Command.config_menus) будет частью cudax_lib.
Что нужно будет делать пользователю, чтобы этот метод получил управление при старте Куд?

**Comment by Alexey-T** [comment]
хм, оказ-я, метод onfocus НЕ вызывается сначала в Вин. Это баг- сорри

**Comment by Alexey-T** [comment]
Beta

**Comment by kvichans** [comment]
Что изменилось?

**Comment by Alexey-T** [comment]
onfocus вызывается при старте. 
в cuda_mn.zip стоит вызов return в onfocus, уберите его.

**Comment by kvichans** [comment]
"при старте" как связан с "при получении фокуса"?
будет вызываться при всех передачах фокуса? 
ждать бету?

**Comment by Alexey-T** [comment]
Бета уже есть
(в каком-то каталоге)
onfocus вызыв. при старте (при показе таба)

**Comment by Alexey-T** [comment]
on-start added. Bt позже. вики уже есть

**Comment by kvichans** [comment]
Ура! Заработало.
1. Готовый плагин [plugin.ConfigMenu.zip](https://github.com/kvichans/cuda_config_menu/releases/download/ver-0.8.0/plugin.ConfigMenu.zip)
2. Как при установке закинуть [menu.json](https://github.com/kvichans/cuda_config_menu/blob/master/menu.json) в папку _settings_?

**Comment by Alexey-T** [comment]
никак при установке. Так можно

**Comment by kvichans** [comment]
"почему"? Я даю плагин, который после установки _готов_ повторить исходное меню Куд. Но для этого нужно где-то найти файл menu.json. Хорошее место для файла, конечно, settings. Но как он туда попадет? Может быть разместить этот файл в папке плагина?

**Comment by Alexey-T** [comment]
в папке плагина (и копировать в sett/ при запуске)

**Comment by kvichans** [comment]
да! я пришел к таком же решению

**Comment by Alexey-T** [comment]
лучше даже не копировать.

**Comment by kvichans** [comment]
> лучше даже не копировать

Поясните
